[project]
name = "local-rag"
version = "0.1.0"
description = "just a local RAG"
readme = "README.md"
authors = [
    { name = "t-ecker", email = "152566019+t-ecker@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-chroma>=1.1.0",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.18.1",
]

[project.scripts]
local-rag = "local_rag.main:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
    "ty>=0.0.69",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "C4", "RUF"]
