[theme]
base = "light"

primaryColor             = "#2138E0"
backgroundColor          = "#EDF0F4"
secondaryBackgroundColor = "#ededed"
textColor                = "#111C26"
borderColor              = "#D3DAE2"

baseRadius       = "full"
showWidgetBorder = true

font = "sans-serif"
headingFont = "monospace"

[browser]
gatherUsageStats = false

[logger]
level = "warning"